MAX_LOG_FILE_SIZE_MB = 10
BYTES_PER_MB = 1024 * 1024
MAX_LOG_FILE_SIZE = MAX_LOG_FILE_SIZE_MB * BYTES_PER_MB

BACKUP_LOG_COUNT = 5
DEFAULT_LOG_DIR = "./logs"
DEFAULT_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"
DEFAULT_LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
